### PR TITLE
fix(video): added reportText, dropped a11yReportText

### LINKED ISSUE #1533: Report text for video is not passed correctly
# Bug Report
## Description
Video doesn't pass report text to the report button correctly 

## Screenshots
Screen Shot 2021-09-29 at 12 00 42 PM

### PR DESCRIPTION
**Pull request by austingardner**
## Description
Fixed Report Text for video and dropped a11yReportText

## References
closes #1533 

## Screenshots
Screen Shot 2021-10-05 at 10 33 39 PM

### CODE REVIEW

File: src/components/ebay-video/component.js [hunk 1]
```diff
@@ -114,6 +114,10 @@ module.exports = {
             this.video.muted = input.muted;
         }
 
+        if (input.reportText) {
```
Comment (agliga) [inline src/components/ebay-video/component.js:117]: Why set it in state? 
Just call it directly from input

**Review by agliga — CHANGES_REQUESTED** [review]
Just change the state to input
Also makes sure you change marko.json too. 
Otherwise it looks good

File: src/components/ebay-video/component.js [hunk 2]
```diff
@@ -224,7 +224,10 @@ module.exports = {
         );
 
         // eslint-disable-next-line no-undef,new-cap
-        shaka.ui.Controls.registerElement('report', new Report.Factory());
+        shaka.ui.Controls.registerElement(
+            'report',
+            new Report.Factory(this.input.reportText || null)
```
Comment (agliga) [inline src/components/ebay-video/component.js:229]: One more nit, sorry. I don't think there's a need to default to null?

You have the same thing here. I would just do `this.input.reportText` here.
https://github.com/eBay/ebayui-core/pull/1532/files#diff-ec1aeb41a76f173410fc83de66c8305a2e27f80a2053cb23a4b638495b445783R34

And same with it on the next one. If it's undefined or blank it should be fine I would assume right?

**Review by agliga — APPROVED** [review]
