### PR TITLE
Carousel: Improve native scrolling animation on IOS.

### LINKED ISSUE #454: Carousel: Native scrolling animation slow in IOS
# Bug Report

## Description
Currently the native inertial scrolling deceleration in mobile safari is much slower than chrome which makes the snap animation look a bit too delayed.

## Screenshots

carousel-ios-native-scrolling

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
This changes the IOS animation such that the transition happens immediately after the `touched` event. It calculates the scroll velocity and moves the user to an appropriate slide.

In chrome (where event.cancelable for touch events is false) we maintain the existing behavior.

## References
fixes #454 

## Screenshots
carousel-updated-animation-ios

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@DylanPiercey Was there an intentional update to yarn.lock?

**Comment by DylanPiercey** [comment]
Removed the `yarn.lock` changes from the PR 😄.

File: src/components/ebay-carousel/utils/scroll-transition/index.js [hunk 1]
```diff
@@ -73,6 +78,7 @@ module.exports = function scrollTransition(el, to, fn) {
  * @param {number} val - A number between 0 and 1.
  * @return {number}
  */
-function easeInOut(v) {
-    return v < 0.5 ? 2 * v * v : -1 + (4 - 2 * v) * v;
+function easeOut(v) {
+    const t = v - 1;
+    return t * t * t + 1;
```
Comment (seangates) [inline src/components/ebay-carousel/utils/scroll-transition/index.js]: I know it's merged but `Math.pow()`, FTW.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow
