### PR TITLE
fix(ebay-textbox): update input interface to include textarea-specifi…

### LINKED ISSUE #2356: ebay-textbox: typescript type check breaks for `step` and other `input` attributes
# Bug Report

## Description

Since `ebay-textbox` only extends `"textarea"`, attributes such as `step` will fail type check

## Workaround

Adding spread props w/ `any`

```
<ebay-textbox
    type="number"
    ...({ step: "0.01" } as any)
/>
```

## Screenshots

image

### PR DESCRIPTION
**Pull request by WinkeeFace**
## Description

Updated the `component-browser.ts` file to reference shared attributes from `tags-html.d.ts` and added the `Textbox` class implementation.

## Context

These changes were made to reduce redundancy and ensure a single source of truth for the attributes used in the `TextboxInput` interface. By referencing the shared attributes, we can maintain consistency and avoid potential errors. Additionally, the `Textbox` class was implemented to handle the floating label functionality and event forwarding.

## References

Fixes #2356 

## Screenshots

N/A

### CODE REVIEW

File: src/components/ebay-textbox/component-browser.ts [hunk 1]
```diff
@@ -95,4 +100,4 @@ class Textbox extends Marko.Component<Input> {
     }
 }
 
-export default Textbox;
+export default Textbox;
```
Comment (LuLaValva) [inline src/components/ebay-textbox/component-browser.ts:103]: Looks like a newline was removed, can you add it back?

**Review by LuLaValva — COMMENTED** [review]
Thanks @WinkeeFace, looks good! Just one quick fix.

Also, can you `npm run change`? Looks like you're missing a changeset, this should be a `patch`.

**Review by LuLaValva — APPROVED** [review]

**Review by agliga — APPROVED** [review]
