### PR TITLE
Textbox: Fix disable capability;

### LINKED ISSUE #669: Textbox: disabled attribute is not working
# Bug Report

## Description
unable to disable a text box.
## Workaround

https://www.loom.com/share/72720438a5af47f584c91ffe5d598f41

 <ebay-textbox disabled />

### PR DESCRIPTION
**Pull request by seangates**
## Description
- adds state with `disabled` property to widget
- adds discrete disabled attribute to text input in the template
- new tests to cover the component when it's disabled to prevent events from firing

## References
Fixes #669

### CODE REVIEW

File: src/components/ebay-textbox/index.js [hunk 1]
```diff
@@ -38,9 +43,11 @@ module.exports = require('marko-widgets').defineComponent({
 
 function forwardEvent(eventName) {
     return function(originalEvent, el) {
-        emitAndFire(this, `textbox-${eventName}`, {
-            originalEvent,
-            value: (el || this.el.querySelector('input, textarea')).value
-        });
+        if (!this.state.disabled) {
```
Comment (ianmcburnie) [inline src/components/ebay-textbox/index.js]: I'm confused as to why these events would get forwarded in the first place if the DOM element is disabled.

Comment (seangates) [reply src/components/ebay-textbox/index.js]: Essentially, our tests “fake” the click, focus, blur, etc. If I were to try and write the test for a disabled state without this check it would always fail.

Should I remove the test in order to remove this check?

Comment (ianmcburnie) [reply src/components/ebay-textbox/index.js]: Thanks for explaining. I don't think we should be adding logic to our code purely for the purpose of our test setup ... if that makes sense.
