### PR TITLE
Listbox: Fix invalid id selector

### LINKED ISSUE #786: listbox: v2.7.0 incompatible with marko@4.18.10
# Bug Report

## Screenshots
image

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
Fixes the listbox element so that it uses a valid class selector instead of a potentially invalid id selector.

## References
Fixes #786

### CODE REVIEW

File: src/components/ebay-listbox-button/index.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ module.exports = require('marko-widgets').defineComponent({
         this.expander = new Expander(this.el, {
             autoCollapse: true,
             expandOnClick: !this.state.disabled,
-            contentSelector: `#${optionsContainer.id}`,
+            contentSelector: `.listbox__options`,
```
Comment (seangates) [inline src/components/ebay-listbox-button/index.js]: Doesn't need backticks now.

Comment (DylanPiercey) [reply src/components/ebay-listbox-button/index.js]: Fixed
