### PR TITLE
Menu: fix shortcut when CAPS-LOCK enabled

### LINKED ISSUE #656: menu: keyboard type-does not work when cap lock is on
# Bug Report

## Description
repro:
go to menu
click on the menu
Type a letter with caps lock on
The matching option is not selected.

can repro it in market place

### PR DESCRIPTION
**Pull request by ianmcburnie**
# Fixes #656 

Now calling `toLowerCase()` on the char that is passed. Also updated tests to check for this.

### CODE REVIEW

File: src/common/nodelist-utils/index.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 // returns index of first node in NodeList with matching first character (case-insenstive)
 function findNodeWithFirstChar(nodeList, char) {
-    return [...nodeList].findIndex((el) => el.innerText.charAt(0).toLowerCase() === char);
+    return [...nodeList].findIndex((el) => el.innerText.charAt(0).toLowerCase() === char.toLowerCase());
```
Comment (agliga) [inline src/common/nodelist-utils/index.js]: Just a quick question, is there a possibility either el.innerText or char will be null? It could cause an error if it does.

Comment (ianmcburnie) [reply src/common/nodelist-utils/index.js]: If called purely as a utility, then yes. From menu component as it stands, I don't believe so.
